name: Build APK - deBruin Chat

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout do repositório
        uses: actions/checkout@v3

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🧶 Instalar Yarn e EAS CLI
        run: |
          npm install -g yarn
          npm install -g eas-cli

      - name: 📦 Instalar dependências do projeto
        run: yarn install

      - name: 🔑 Verificar autenticação Expo
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 📤 Build APK com EAS
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
